---
signer-config:
  local:
keypair: "AD3QomzzUMFPLnivUyXrJKUqZznHX2A6ib/e6OVHcCL3"
rpc-host-ip: 0.0.0.0
rpc-port: 8080
metrics-port: 9184
gas-pool-config:
  redis:
    redis_url: redis://default:vCzsyPcCMaUMHTjhuaKXMzkiITqidWMX@kodama.proxy.rlwy.net:10310
fullnode-url: https://fullnode.mainnet.sui.io:443
coin-init-config:
  target-init-balance: 500000000
  refresh-interval-sec: 86400
daily-gas-usage-cap: 2000000000000
advanced-faucet-mode: false
