---
signer-config:
  local:
    keypair: "suiprivkey1qq7apgnv7dgvznew0zh4xf0tyjjj5eeeca0kqw5fhl0w3e28wq30w4q5hyc"
rpc-host-ip: 0.0.0.0
rpc-port: 8080
metrics-port: 9184
gas-pool-config:
  redis:
    redis_url: redis://default:vCzsyPcCMaUMHTjhuaKXMzkiITqidWMX@kodama.proxy.rlwy.net:10310
fullnode-url: https://fullnode.mainnet.sui.io:443
coin-init-config:
  target-init-balance: 500000000
  refresh-interval-sec: 86400
daily-gas-usage-cap: 2000000000000
advanced-faucet-mode: false
